var fs = require('fs');
var toc = require('markdown-toc');

let md = fs.readFileSync('./src/README.md', 'utf8');
md = toc.insert(md);

fs.writeFileSync('./README.md', "<!-- !!!! DO NOT EDIT THIS FILE !!!! edit src/README.md INSTEAD and run node buildToc.js !!!! -->\r\n" + md );